WIP

diff --git a/scripts/cti b/scripts/cti
--- a/scripts/cti
+++ b/scripts/cti
@@ -91,6 +91,12 @@ kube_wait_pod () {
   exit 1
 }
 
+kube_cleanup() {
+  echo "Cleaning up kubernetes pods after receiving SIGINT"
+  kubectl --context="${K8S_CONTEXT}" delete pods "${CLUSTER_TEST_POD}" || true
+  kubectl --context="${K8S_CONTEXT}" delete pods -l libra-node=true --grace-period=0 --force || true
+}
+
 while (( "$#" )); do
   case "$1" in
     --k8s)
@@ -202,16 +208,17 @@ else
     echo "kubectl is not installed. Please install kubectl. On mac, you can use : brew install kubectl"
     exit 1
   fi
+  trap kube_cleanup SIGINT
   echo "Running cluster-test on Kubernetes"
   kube_init_context
-  pod_name="cluster-test-$(whoami)-$(date +%s)"
-  pod_name=${pod_name/_/-} #underscore not allowed in pod name
+  CLUSTER_TEST_POD="cluster-test-$(whoami)-$(date +%s)"
+  CLUSTER_TEST_POD=${CLUSTER_TEST_POD/_/-} #underscore not allowed in pod name
   specfile=$(mktemp)
   echo "Pod Spec : ${specfile}"
   join_args $*
   join_env_vars $ENV
   DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
-  sed -e "s/{pod_name}/${pod_name}/g" \
+  sed -e "s/{pod_name}/${CLUSTER_TEST_POD}/g" \
       -e "s/{image_tag}/${TAG}/g" \
       -e "s/{env_variables}/${retval_join_env_vars}/g" \
       -e "s/{extra_args}/${retval_join_args}/g" \
@@ -221,9 +228,9 @@ else
     WORKSPACE=${retval_kube_select_cluster}
   fi
   echo "Using cluster : ${WORKSPACE}"
-  context=${K8S_CONTEXT_PATTERN/CLUSTERNAME/${WORKSPACE}}
-  kubectl --context=${context} apply -f ${specfile} || (echo "Failed to create cluster-test pod"; exit 1)
-  kube_wait_pod ${pod_name} ${context}
+  K8S_CONTEXT=${K8S_CONTEXT_PATTERN/CLUSTERNAME/${WORKSPACE}}
+  kubectl --context=${K8S_CONTEXT} apply -f ${specfile} || (echo "Failed to create cluster-test pod"; exit 1)
+  kube_wait_pod ${CLUSTER_TEST_POD} ${K8S_CONTEXT}
   echo "**********"
   echo "${BLUE}Dashboard:${RESTORE} http://grafana.${WORKSPACE}-k8s-testnet.aws.hlw3truzy4ls.com/"
   echo "${BLUE}'validator-0' Logs:${RESTORE} http://kibana.${WORKSPACE}-k8s-testnet.aws.hlw3truzy4ls.com/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))&_a=(columns:!(log,kubernetes.pod_name),filters:!(('\$state':(store:appState),meta:(alias:!n,disabled:!f,key:kubernetes.pod_name,negate:!f,params:(query:validator-0),type:phrase),query:(match:(kubernetes.pod_name:(query:validator-0,type:phrase))))),interval:auto,query:(language:kuery,query:''),sort:!(!('@timestamp',desc)))"
@@ -232,7 +239,7 @@ else
   echo
   echo "${BLUE}Note:${RESTORE} Because of log volume, logs for only some of the validators and fullnodes are streamed to Kibana."
   echo "**********"
-  kubectl --context=${context} logs -f "${pod_name}" | tee $OUTPUT_TEE
+  kubectl --context=${K8S_CONTEXT} logs -f "${CLUSTER_TEST_POD}" | tee $OUTPUT_TEE
 fi
 
 if [ ! -z "$REPORT" ]; then
